### ISSUE TITLE
Annotated image is not saved

### ISSUE THREAD

**Issue by fahriwps** [jingdao/IR_detection#4]
So I tried to run annotation.py with my own dataset and with my custom margin, after I finished to annotate and closed the annotation tool, I saw my label1.png and the rest of my labeled images were just black, no segmented label from annotation.py was saved. Was it normal or did I do it wrong? Thanks

**Comment by jingdao** [comment]
This issue should be fixed in the latest [commit](https://github.com/jingdao/IR_detection/commit/848c23904901e6701f5ad4899cc5d378cf26512f). After you have finished annotating the input image, type the "space" character, and a black and white annotation image should be saved at label1.png.
